version: '3' 

services:
  mongo:
    image: 'mongo:6.0.4'
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - './data/db:/data/db'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret

  server:
    image: 'plasma-server'
    build: ./application/plasma-server
    environment:
      - RUST_LOG=info
    ports:
      - '8000:8000'
    depends_on:
      - mongo
    
